[package]

name = "rtracker"
version = "0.2.0"
authors = ["Justin Noah <justinnoah@gmail.com>"]

[dependencies]
bincode         = "0.0.9"
docopt          = "0.6.39"
rand            = "0.1.3"
rusqlite        = "0.0.9"
rustc-serialize = "0.2.15"
time            = "0.1.17"

[[bin]]
name = "rtracker"
path = "src/main.rs"
