[package]

name = "rtracker"
version = "0.2.0"
authors = ["Justin Noah <justinnoah@gmail.com>"]

[dependencies]
bincode         = "0.1.2"
docopt          = "0.6.62"
rand            = "0.3.7"
rusqlite        = "0.0.17"
rustc-serialize = "0.3.12"
time            = "0.1.24"

[[bin]]
name = "rtracker"
path = "src/main.rs"
