[package]

name = "rtracker"
version = "0.2.0"
authors = ["Justin Noah <justinnoah@gmail.com>"]

[dependencies]
bincode         = "0.0.10"
docopt          = "0.6.44"
rand            = "0.1.4"
rusqlite        = "0.0.10"
rustc-serialize = "0.3.1"
time            = "0.1.19"

[[bin]]
name = "rtracker"
path = "src/main.rs"
