[package]
name = "rtracker"
version = "0.4.999"
authors = ["Justin Noah <justinnoah@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "~0.8"

[dependencies]
chrono          = "~0.2"
docopt          = "~0.6"
env_logger      = "~0.3"
log             = "~0.3"
rand            = "~0.3"
rustc-serialize = "~0.3"
rust-ini        = "~0.9"
serde           = "~0.8"

[dependencies.bincode]
version = "~0.6"
default-features = false
features = ["serde"]

[dependencies.rusqlite]
version = "~0.7"
default-features = false
features = ["chrono", "serde_json"]

[[bin]]
name = "rtracker"
path = "src/main.rs"
