[package]

name = "rtracker"
version = "0.3.0"
authors = ["Justin Noah <justinnoah@gmail.com>"]

[dependencies]
bincode         = "0.3.0"
docopt          = "0.6.66"
rand            = "0.3.8"
rusqlite        = "0.1.0"
rustc-serialize = "0.3.15"
rust-ini        = "0.8.0"
time            = "0.1.26"

[[bin]]
name = "rtracker"
path = "src/main.rs"
